### ISSUE TITLE
default mapper with functions

### ISSUE THREAD

**Issue by achtan** [kadirahq/react-simple-di#1]
Why default mapper looks like this:

```
const defaultMapper = (context, actions) => ({
  context: () => context,
  actions: () => actions
});
```

"with functions" and not just like this:

```
const defaultMapper = (context, actions) => ({
  context: context,
  actions: actions
});
```

?

**Comment by arunoda** [comment]
Somehow, I don't like to pass a big object over React props. 
It's feels nice for me to pass a function instead.

**Comment by lsunsi** [comment]
I had the same doubt haha

**Comment by macrozone** [comment]
I thought it was to prevent accidental using of context directly in the wrapped component ;-)
